require: rubocop-rails

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/**/*'
